### ISSUE TITLE
Example provided is non-accessible

### ISSUE THREAD

**Issue by walesmd** [richardvenneman/floatl#1]
The example provided within the README.md file does not associate the `label` element with a particular `input` element, preventing assistive technologies from being able to describe form elements to their users. Suggest updating the following example in the README.md:

```
<div class="floatl">
  <label class="floatl__label" for="firstName">First name</label>
  <input class="floatl__input" placeholder="First name" type="text" id="firstName">
</div>
```

It's probably worthwhile to test this library as well with the following pattern, which is common and removed the need for the `for` attribute:

```
<div class="floatl">
  <label class="floatl__label">First name
    <input class="floatl__input" placeholder="First name" type="text">
  </label>
</div>
```

**Comment by richardvenneman** [comment]
Hey @walesmd, thanks for reporting this issue.

I'm of course willing to update the example and compatibility to ensure support for assistive technologies. Do you have an article on compatibility with the implementation you suggested?

Thanks.
