### ISSUE TITLE
Missing label or input class breaks JS

### ISSUE THREAD

**Issue by leptest** [richardvenneman/floatl#14]
If there is no "floatl__label" or "floatl__input" class on the elements, JS throws "Uncaught TypeError: Cannot read property 'addEventListener' of undefined"

http://codepen.io/leptest/pen/QKrjJY

**Comment by richardvenneman** [comment]
Hey @leptest thanks for reporting this issue and the pull request!

It's great to avoid the TypeError. However, I think it would be better a better experience if we could inform the user with a descriptive error message. How about throwing an `ArgumentError` like so?

``` javascript
if (!this.label) throw new ArgumentError(`No label element was found. Markup your label element with the correct floatl class.`);
if (!this.input) throw new ArgumentError(`No input element was found. Markup your input element with the correct floatl class.`);
```

**Comment by leptest** [comment]
You're welcome!

And you're also correct about providing feedback to the user about the error.  I'm taking a look at it just now and will update the pull request.

**Comment by leptest** [comment]
Do you think execution should stop if there is an error, or continue on to the other form elements?

**Comment by richardvenneman** [comment]
@leptest I think execution should stop (which will happen when throwing an `ArgumentError`). The component doesn't have much use unless both elements are available and functional.

**Comment by leptest** [comment]
Thanks for the feedback @richardvenneman. I completely agree that the component should always be complete and functional.

However, we have a situation where a CMS is generating multiple forms in various sections of the site, and there are edge cases where the input (and potentially the label) will not get the correct class (it does get the wrapping class). At this point, the entire web page breaks.

Do you think there is a slightly different way we could handle the error that provides feedback but also allows other JS functionality to continue?

**Comment by richardvenneman** [comment]
@leptest I see. Would it be possible for you to wrap the Floatl instantiation in a `try...catch` statement, catching the `ArgumentError`?

Another solution that comes to mind is to `console.warn` the messages in development. But that would require to strip the console statements when bundling (with something like [strip-loader](https://www.npmjs.com/package/strip-loader)), which is slightly more involved.

**Comment by leptest** [comment]
What about something like this?

``` javascript
try {
    if (!this.label) {
        throw new Error('No label element was found. Markup your label element with the correct floatl class.');
    }
    if (!this.input) {
        throw new Error('No input element was found. Markup your input element with the correct floatl class.');
    }
    this._bindListeners();
    this._init();
}
catch (err) {
    console && console.error && console.error(err);
}
```

**Comment by leptest** [comment]
I tried wrapping the Floatl in a try catch, though it then achieved part of the setup on each input/label pair and left them half complete.

**Comment by leptest** [comment]
Any further suggestions on this?

**Comment by richardvenneman** [comment]
@leptest Sorry for the lack of reply.

Of course I'd like to help with your use case but meanwhile I'd like to have a pragmatic solution as possible in place. I'll try to have a look at this later today.

**Comment by leptest** [comment]
No problem!

Would you like me to further detail the requirements/expected behaviour?

**Comment by richardvenneman** [comment]
@leptest Sure! That would help.

**Comment by leptest** [comment]
Here are the key points we've been discussing. My views differ slightly, but we're pretty close.
- Each input/label pair that floatl updates should work completely or not at all.
- floatl should skip a "broken" pair of elements.
- If a broken pair is skipped, a descriptive message should be displayed to the developer/user.
- Execution should not stop if there is an error. It should not break other JS on the page.
- The error message should not rely on `console.log()`

What do you think?

**Comment by richardvenneman** [comment]
Great summarisation, we're definitely on the same page here.

I currently cannot think of a solution where we 1) inform the developer with a descriptive message 2) don't rely on console logging. So maybe we should just keep it simple instead, trusting that the developer who implements this library correctly marks up their html.

So what about a simple check with return statement before binding listereners/initialization? This is very similar to your initial pull request, except that I prefer a guard clause over an if expression:

``` javascript
constructor(element) {
  this.element = getElement(element);
  this.label = this.element.querySelectorAll('.floatl__label')[0];
  this.input = this.element.querySelectorAll('.floatl__input')[0];

  if (!this.label || !this.input) return;
  this._bindListeners();
  this._init();
}
```

Can you confirm that this will work in your case? If so, I can fix the issue with a new commit, or you can rebase and update your pull request.

**Comment by leptest** [comment]
Thanks for the reply. Yeah it makes sense about the console logging, and I agree about trusting the developer. 

That solution looks good too!

I'll update the pull request in about an hour and hopefully we can close the issue.

Cheers

**Comment by leptest** [comment]
It looks like the pull request has been updated. Not 100% sure though. Please let me know if I need to do anything else.

**Comment by richardvenneman** [comment]
Looks good! I will build and release an updated version shortly. Thanks for your patience!

**Comment by leptest** [comment]
Amazing. Thanks so much for you time and help!
