### ISSUE TITLE
utils.js:removeClass:24, the 're' variable scope issue

### ISSUE THREAD

**Issue by martinothamar** [richardvenneman/floatl#16]
Hey!

[https://github.com/richardvenneman/floatl/blob/master/src/js/utils.js#L24](https://github.com/richardvenneman/floatl/blob/master/src/js/utils.js#L24)

We have an ASP.NET application where this variable is assigned to global scope and prevents minification.
I can submit pull-request if you want.

**Comment by richardvenneman** [comment]
Hey @martinothamar, thanks for reporting this issue!

It seems I forgot to properly replace that instantiation while rewriting this library from CoffeeScript. Should have used a linter! I'll fix this and release a new version shortly.

**Comment by martinothamar** [comment]
Cool, thanks!

**Comment by richardvenneman** [comment]
@martinothamar just released a new version!

**Comment by martinothamar** [comment]
Awesome, many thanks. 👍
