### ISSUE TITLE
Using classList instead of custom methods?

### ISSUE THREAD

**Issue by davidbgk** [richardvenneman/floatl#4]
First, thanks for your work :)

I'm curious about the reason you added your own utilities instead of using `classList` that is [quite well supported now](http://caniuse.com/#feat=classlist).

**Comment by richardvenneman** [comment]
Hey @davidbgk, thanks :)

To be honest I didn't look into the `classList` API yet, but it looks really convenient. It looks like it is supported from IE10, but unfortunately we still have quite some users on IE9.. I plan to keep this library compatible with >= IE8.

FYI I applied the technique described on [You Might Not Need jQuery](http://youmightnotneedjquery.com/#add_class).

**Comment by davidbgk** [comment]
Oh I missed that in `utils`, thanks!
